default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USER") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'root' } %>
  host: <%= ENV.fetch("DB_HOST") { '' } %>

development:
  <<: *default
  database: sample_graphql_rspec_dev

test:
  <<: *default
  database: sample_graphql_rspec_test

production:
  <<: *default
  database: sample_graphql_rspec_production
  username: sample_graphql_rspec
  password: <%= ENV["SAMPLE_GRAPHQL_RSPEC_DATABASE_PASSWORD"] %>
